### ISSUE TITLE
Scala 2.11 builds

### ISSUE THREAD

**Issue by seddonm1** [opencypher/morpheus#917]
Hi,
Your README says:

> As of Morpheus 0.3.0, the project has migrated to Scala 2.12 and Spark 2.4 series. As of Spark 2.4.1 Scala 2.12 is the default Scala version for Spark, and Morpheus is attempting to mimic this.

However after a few bad releases Spark at version 2.4.3 has switched back to Scala 2.11 for primary releases. 

Is it possible to publish 2.11 builds too as changing the Scala version in build.params.gradle alone does not compile.

Thanks

**Comment by Mats-SX** [comment]
Hello @seddonm1 

You're right that Spark switched back to using 2.11 by default. I will modify our README to reflect this fact.

However, that was not the main reason for us to switch Morpheus over to 2.12. We did that in preparation for Spark 3.0, which is going to leave 2.11 behind altogether ([link](https://github.com/apache/spark/pull/23098)), and also to reduce the effort we would have to cross-build and cross-test all of our modules.

Unfortunately, we are unable to reprioritise on this issue, but we will stick with 2.12 only, even though Spark has changed back to offer 2.12 as non-default, non-prebuilt support. It is still possible to build your own Spark using 2.12 and use Morpheus with it, or to use the `2.4.2` prebuilt binaries.

Since a significant portion of this project will be made official with Spark 3.0, this is where we are focusing most of our efforts currently.

Apologies for the inconvenience
Regards
Mats
