### ISSUE TITLE
need instructions on okapi

### ISSUE THREAD

**Issue by bluejoe2008** [opencypher/morpheus#945]
hi, i noticed the `okapi` module in `morpheus`
some traits such as `PropertyGraph` and `CypherSession` are defined in `okapi`, 
that seems it is ready to be used to build custom Cypher execution engines

do you have any instructions or example code of how to use `okapi`?

thank you!

**Comment by Mats-SX** [comment]
Hello @bluejoe2008 and thanks for reaching out to us!

You are quite right, the design intention for `okapi` is to be used as an abstract query engine to be applied to any backend in order to implement Cypher querying support. There are multiple layers on the `okapi` stack with which you can hook into the engine. The most sophisticated is the `okapi-relational` layer, which assumes a table-like backend system (such as Apache Spark, which we have used as the driving backend for `okapi`, and the main feature of `Morpheus`).

We have done a number of talks on `okapi`:

* [openCypher Implementers Meeting (oCIM) 5, March 2019](https://s3.amazonaws.com/artifacts.opencypher.org/website/ocim5/slides/ocim5+-+CAPS+%2B+GraphDDL.pdf)
* [Apache Spark Summit EU 2019 - SparkGraph](https://databricks.com/session_eu19/graph-features-in-spark-3-0-integrating-graph-querying-and-algorithms-in-spark-graph)
* [Apache Spark Summit EU 2019 - Morpheus](https://databricks.com/session_eu19/extending-spark-graph-for-the-enterprise-with-morpheus-and-neo4j)

To mention a few. I hope these talks can be useful.

Unfortunately, we do not have any updated documentation for `okapi` in particular, and we are not actively developing either `okapi` or `morpheus`. There are also two sibling projects that use `okapi` on other backends:

* https://github.com/opencypher/link (Apache Flink)
* https://github.com/s1ck/mem-cypher (In-memory Scala data structures)

but these are also not being actively developed.

**Comment by bluejoe2008** [comment]
ok, many thanks!

**Comment by Mats-SX** [comment]
I'm glad you like it! 😃 

Technically, `okapi` is less about Neo4j (the database) and more about Cypher (the query language) but they do share history and indeed we who built this are with Neo4j (the company).

If/when you try out `okapi` please do reach back here for additional questions and we'll do our best to help out!

Sincerely,
Mats
