### ISSUE TITLE
`create (n)` statement not supported

### ISSUE THREAD

**Issue by bluejoe2008** [opencypher/morpheus#954]
I want to use `okapi` to enable insert nodes/edges into graph via using cypher statements like `create (n)`
however it throws exception on `IRBuilder.process()` which tell `create` statement is unknown
can you give me any suggestion?

Thank you very much!

**Comment by Mats-SX** [comment]
Hello @bluejoe2008 and thanks for reaching out to us.

First, I'd like to clarify the status of this project as currently not being in development. You can read a more comprehensive answer on why in #950.

Second, the updating clauses of Cypher were not in scope for Morpheus even when development was active. This includes the clauses `CREATE`, `MERGE`, `SET`, `DELETE`, and `REMOVE`. In order to create graphs, you will have to make use of the Property Graph Data Sources (PGDS), which provide endpoint-specific formats where nodes can be added in various ways. For example, you can create nodes with full Cypher support in a Neo4j database and connect it to Morpheus using a Neo4j PGDS ([example](https://github.com/opencypher/morpheus/blob/master/morpheus-examples/src/main/scala/org/opencypher/morpheus/examples/Neo4jWorkflowExample.scala#L50)). Or, you can use Scala case classes and create nodes (and relationships) in Scala code and create a Morpheus graph directly from these ([example](https://github.com/opencypher/morpheus/blob/master/morpheus-examples/src/main/scala/org/opencypher/morpheus/examples/CaseClassExample.scala)).

I hope this is helpful!
Regards
Mats
