### ISSUE TITLE
How to persistent the PropertyGraph object to disk and load it back to memory?

### ISSUE THREAD

**Issue by ministat** [opencypher/morpheus#960]
When running cypher query for the same node/relation tables, I have to create the PropertyGraph every time. If the node/relation tables are huge on HDFS and those data needs some tranformation to be coverted to CAPSEntityTable, it will be a big overhead.

Is it possible to persistent the PropertyGraph to disk and load it to memory next time? 

The PropertyGraph is created every time: https://github.com/opencypher/morpheus/blob/master/morpheus-examples/src/main/scala/org/opencypher/morpheus/examples/DataFrameInputExample.scala#L62

**Comment by s1ck** [comment]
Hey @ministat 

Creating a property graph from existing data frames does not really involve any transformation. Node and relationship tables are just wrappers with constraints on column names and types. If you need to transform your input data in order to make it fit for Morpheus, it would make more sense to persist those data frames (in any way you prefer) before you create the tables and load from there.

Also keep in mind that this project is no longer maintained, so there will not be any feature development nor support work from the Neo4j side.

**Comment by ministat** [comment]
@s1ck Thanks for your reply. I'm thinking how to create a view for the wrapper in application level.
